basic_portfolio/urls.py
from django.urls import path, include
from basic_portfolio import views

app_name = 'basic_portfolio'

urlpatterns = [
    path('university_projects/', views.uniprojects, name='uniprojects'),
    # path('about/', views.about, name='about'),
    path('contact/', views.contactform, name='contactform'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_portfolio import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('projects/', include('basic_portfolio.urls')),

]

basic_portfolio/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    email = models.EmailField(blank=True)
    subject = models.CharField(max_length=128, blank=True)
    message = models.CharField(max_length=256, blank=True)

    def __str__(self,):
        return self.from_email

    def __str__(self):
        return self.subject

    def __str__(str):
        return self.message

basic_portfolio/forms.py
from django import forms
from basic_portfolio.models import Contact

class NewContact(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea, required=True)
    class Meta:
        model = Contact
        fields = ('email', 'subject', 'message')

basic_portfolio/views.py
from django.shortcuts import render
# Create your views here.
from basic_portfolio.forms import NewContact

def index(request):
    return render(request, 'basic_portfolio/index.html')

def uniprojects(request):
    return render(request, 'basic_portfolio/university_projects.html')

# def about(request):
#     return render(request, 'basic_portfolio/aboutme.html')

def contactform(request):
    form = NewContact

    if request.method == 'POST':
        form = NewContact(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR')

    return render(request, 'basic_portfolio/contact.html', {'form':form})

templates/basic_portfolio/aboutme.html
{% extends "basic_portfolio/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/aboutme.css' %}">

<div class="header">
  <div class="p-5 mt-5">
    <h1 class="aboutme" align="center">About Me</h1>
    <p class="short-intro mt-5 ps-5 pe-5" align="start">
      I’m a Computer Science (Network Computing) graduate from Brunel University London, having achieved 2.1 with Honours.
      I enjoy taking on challenges as it enables me to think differently and take me out of my comfort zone. I simply love
      learning and building new experiences.<br>
    </p>
  </div>
</div>


<div class="container">
  <div id="more-aboutme" class="p-5">
    <h5>Long-term Goal</h5>
    I am aiming to become a Full Stack Developer, to be able to create cross-platform web and mobile applications. Having
    said that, this includes Software Developer/Engineering (Front-end and/or Back-end), DevOps and Testing/QA. To learn all
    of these technologies is a long-term goal.<br><br>
    <h5>For now</h5>
    For now, I would love to dive into anyone of these roles and have a core focus!<br><br>
    <h5>Passion</h5>
    I have begun to read documentation on JavaScript, React and soon more about jQuery, I am learning the fundamentals of these
    and in the process of building a project based on React-Native framework. The first project will be a mobile and TV application.
    I also have the desire to learn Python, from June 2021 to August 2021 I have taken a course known as Python and Django Full Stack
    Web Developer Bootcamp. This opened me up to Python, Django, JavaScript. jQuery, HTML, CSS and Bootstrap, understanding the
    syntax and object oriented programming. This website is powered by Django, I will set up the contact form using Python.<br><br><br>
    <img id="aboutme_img" src="{% static 'images/aboutme.jpg'%}" alt="">
  </div>
</div>


<div id="myStack" class="container hide">
  <!-- <div class="container d-grid gap-5"> -->

  <div class="container p-5">
    <div class="row">
      <div class="col-lg-4 align-self-center col-md-6 col-xs-6 boxy pb-5">
        <h1 class="mystack" align="left">Core tools and technologies</h1><br>
      </div>
      <div class="col-lg-4 align-self-center col-md-6 col-xs-6 boxy pb-5">
        During my university studies, I have had extensive exposure to Java programming language including completing weekly programming challenges set on a deadline basis, these were based on algorithms and data structures.
        <br><br>
        Each year I have been involved in a core project where the first two years of my studies has involved group projects; building skills on teamwork and collaboration via Git version control and GitHub.
        <br><br>
        The collage represents all the core skillsets I have built over the course of three years, including the software development lifecycle and agile methodologies.
      </div>
      <div class="col-lg-4 col-md-6 col-xs-6 boxy pb-5">
        <img id="mystack_collage" src="{% static 'images/mystack_collage.jpg' %}" alt="">
      </div>
    </div>
  </div>
</div>

<!-- <div class="container p-5 top-level">
  <div class="row inner-level">
    <div id="mobile-top" class="col-lg-4 align-self-center col-md-6 col-xs-6 boxy pb-5 mobile-top">
      <h1 class="mystack" align="left">Familiarity of tools and technologies</h1><br>
    </div>
    <div class="col-lg-4 align-self-center col-md-6 col-xs-6 boxy pb-5 mobile-middle">
      Upon completing my studies, I have grown a hunger to learn various technologies and how they interconnect. This is why I have taken a course on Python and Django Full Stack Web Development Bootcamp. To be exposed to Python and JavaScript and having the understanding of the core fundamentals.
      <br><br>
      I have yet to build projects on these and will do so in the coming months. This course has given me the basic understanding on how to start Django applications and working on the backend using Python and utilising Python Shell Scripting.
      <br><br>
      Now, React is another technology that deeply interests me as it caters for web and cross-platform mobile applications. In the coming months, I will be uploading some interesting projects.

    </div>
    <div id="mobile-bottom" class="col-lg-4 align-self-center col-md-6 col-xs-6 boxy pb-5 mobile-bottom">
      <img id="mystack_collage" src="{% static 'images/famwith_collage.jpg' %}" alt="">
    </div>
  </div>
</div> -->
{% endblock %}

templates/basic_portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0, miniman-scale=1.0, maximum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi">
    <!-- <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=0.7, maximum-scale=1, user-scalable=no"> -->


    <title>Abdul Naseem Khan</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@600&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gentium+Book+Basic:wght@700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.13.0/devicon.min.css">

  </head>
  <body>

    <nav class="navbar fixed-top navbar-expand-lg" id="nav-navbar">
      <div class="container">
        <a class="navbar-brand text-dark" href="{% url 'index' %}"> <img src="{% static 'images/newlogo3.png' %}" alt=""> </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="" role="button" ><i class="fa fa-bars" aria-hidden="true" style="color:#E85D04"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="mx-auto"></div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link text-nav" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-nav" href="{% url 'basic_portfolio:uniprojects' %}">University Projects</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link text-nav" href="{% url 'basic_portfolio:about' %}">About</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link text-nav" href="{% url 'basic_portfolio:contactform' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    {% block content %} {% endblock %}

    <!-- <div id="footer">
      <div class="container">
        <p id="left">Email: abdulnaseem548@gmail.com</p>
        <p id="right">
          <a href="https://www.linkedin.com/in/abdul-naseem-khan-14b429198/"> <img src="{% static 'images/linkedin2.png' %}" alt=""> </a>
        </p>
      </div>
      Abdul Naseem Khan &copy; 2021
    </div> -->
    <!-- <footer>
      <div class="row">
        <div class="col col-xs-6 content left">Email: abdulnaseem548@hotmail.com</div>
        <div class="col col-xs-6 content right"> <a href=""> <img src="{% static 'images/linkedin2.png' %}" alt=""> </a> </div>
      </div>
    </footer> -->
    <footer class="text-center text-lg-start text-light">
      <!-- Section: Social media -->
      <section class="d-flex justify-content-center justify-content-lg-between ps-5 pe-5">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <span class="footer-text">Email: abdulnaseem548@gmail.com</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div class="linkedin">
          <a href="https://www.linkedin.com/in/abdul-naseem-khan-14b429198/" class="me-4 text-reset">
            <i id="linkedin" class="fa fa-linkedin-square" style="font-size: 2em;"></i>
          </a>
        </div>
        <!-- Right -->

      </section>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static "js/main.js" %}"></script>

  </body>
</html>

templates/basic_portfolio/contact.html
{% extends "basic_portfolio/base.html" %}
{% block content %}
<link rel="stylesheet" href="/css/contact.css">


<div class="container my-3 d-grid gap-5 p-5 rounded" id="projects">

      <div class="p-5 border">
        <div class="col text-center">
          <h4>Contact</h4>
        </div>

        <form method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Submit">
        </form>

      </div>
</div>

{% endblock %}

templates/basic_portfolio/index.html
{% extends "basic_portfolio/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/index.css' %}">

<style>
  .banner-image {
    background-image: url('static/images/pexels2.jpg');
    background-size: cover;
  }
  /* .hide {
      opacity:0;

  } */
  /* @keyframes wipe-enter {
  	0% {
  		transform: scale(0, .025);
  	}
  	50% {
  		transform: scale(1, .025);
  	}
  } */
  .show {

  }
  @media (max-width: 576px) {
    .banner-image {
      padding-top: 100px;
    }
  }
  @media (max-width: 768px) {
    .banner-image {
      padding-top: 200px;
    }
  }
</style>

<div class="banner-image w-100 vh-100 d-flex justify-content-center align-items-center">
  <h1 class="text-white" id="header-text1">Hello, <br>I am Naseem.</h1>
  <div class="content text-center">
    <h1 class="text-white" id="header-text2">
      Computer Science (Network Computing) Graduate <br>
      Achieved 2.1 with Honours <br>
      A technology enthusiast who loves to learn and adapt.
    </h1>
    <button id="button" class="btn btn-primary btn-md" type="button" onClick="location.href=' {% url 'basic_portfolio:aboutme' %} '">Learn more</button>
  </div>
</div>

<script src="{% static 'js/index.js' %}"></script>

{% endblock %}

templates/basic_portfolio/university_projects.html
{% extends "basic_portfolio/base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/uniproj.css' %}">

<div class="header p-5" id="header">
  <h1 class="header-text mt-5" align="center">Brunel University London</h1>

</div>


      <div class="pt-3 ps-3 pe-3">
        <div class="col text-center pt-4">
          <button id="grad-cert-link" class="btn btn-primary btn-md" type="button" onclick="window.open('https://www.linkedin.com/posts/abdul-naseem-khan-14b429198_graduate2021-brunelgrad2021-computerscience-activity-6836617307985371136-5Kgg', '_blank')">View Graduate Certificate</button>
          <h3>University Projects</h3>
        </div>
      </div>

<div class="container pb-3 ps-3 pe-3 rounded" id="projects">
  <!-- <div class="container my-3 d-grid gap-5 p-5 rounded" id="projects"> -->

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>Pain Management Report (Dissertation)</h4>
        </div>
        <p class="p-3">
          Aim was to develop a 3D pain reporting application that allows users to interact with a 3D human anatomy and to be able to self-report their pain.
          <ul>
            <li>Produced the Systems Development LifeCycle with elements of Scrum suggesting application uses, programming practises (XP), testing (TDD) evaluation method (SUS Questionnaire) and sprint cycle.</li>
            <li>Designing the applications functionality by using the Multi-Tier Client-Server Architecture entailing communication between client (XML), application server (Java) and database server (Java with SQLite).</li>
            <li>Designing the prototype through the use of Marvel app.</li>
            <li>Implemented the OpenGL-ES API and parsed the 3D .obj file (issues with dependencies caused this to fail during testing).</li>
            <li>Have also utilised Unity platform to test and display the 3D human anatomy upon failure.</li>
            <li>Core tools & technologies:
              <ul>
                <li>Java | XML | Java with SQLite | Android | OpenGL-ES API | Unity</li>
              </ul>
            </li>
          </ul>
        </p>
        <div class="d-flex justify-content-center">
          <iframe width="350" height="200" src="https://www.youtube.com/embed/4ufZ9FBto0s?rel=0&amp;&mute=1" frameborder="0" allowfullscreen></iframe>
        </div>
        <div class="col text-center pt-4">
          <button id="button" class="btn btn-primary btn-md" type="button" onclick="window.open('https://github.com/abdulnaseem/pain-management-report', '_blank')">GitHub</button>
        </div>
      </div>

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>Car Park Management System</h4>
        </div>
        <p class="p-3">
          The purpose of this system was to utilise threads with locks, when threads are concurrently running, one thread has control upon the lock while the rest of the threads are waiting. In this example, I have applied it in a car park management system:
          <ul>
            <li>Produced a multi-threading client-server system by adopting the Systems Development LifeCycle, designed using central server algorithm and a protocol table for message passing.</li>
            <li>Four clients (cars) where two are for entering car park and the two for exiting.</li>
            <li>One server that utilizes threading and locks and identifies if the car park is at maximum capacity, if so, then place the two clients in a queue.</li>
            <li>Utilized Power Shell scripting to execute and test the program.</li>
            <li>Core tools & technologies:
              <ul>
                <li>Java | Concurrency | Multi-Threading (Multi Client-Server Communication) | Locking</li>
              </ul>
            </li>

          </ul>
        </p>
        <div class="col text-center">
          <button id="button" class="btn btn-primary btn-md" type="button" onclick="window.open('https://github.com/abdulnaseem/car-park-management-system', '_blank')">GitHub</button>
        </div>
      </div>

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>ParkNow (Android Application)</h4>
        </div>
        <p class="p-3">
          For this project, I was assigned to a group of six in order to identify a problem and as a team come up with solutions.
          The team and I came up with a number of requirements and utilised Scrum to seperate these into seven distinct sprints,
          each sprint was evaluated before moving onto the next. And was assigned to a particular member of the group.
          Git version control was employed to commit these sprints onto GitHub throughout the lifetime of the project.
          <ul>
            <li>Problem: Issue finding parking space in or around the city of London without getting a ticket.</li>
            <li>Solution (app): Explore neighbouring parking space made available by rentors and become a rentee for the desired time limit.</li>
            <li>Core responsibilities, tools & technologies:
              <ul>
                <li>Booking activity | Front-end Development | Android development | Git | XML | Java | NoSql (Firebase database) | Google Maps API</li>
              </ul>
            </li>
          </ul>
        </p>
        <div class="d-flex justify-content-center">
          <iframe width="350" height="200" src="https://www.youtube.com/embed/TBZ_D_UnSQk?rel=0&amp;&mute=1" frameborder="0" allowfullscreen></iframe>
        </div>
        <div class="col text-center pt-4">
          <button id="button" class="btn btn-primary btn-md" type="button" onclick="window.open('https://github.com/abdulnaseem/park-now', '_blank')">GitHub</button>
        </div>
      </div>

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>Vending Machine for Custom-Printing Books 'On Demand' (Prototype)</h4>
        </div>
        <p class="p-3">
          The team (group of 6) and I was given this assignment to build a prototype for those who wish to buy a book through vending machine
          and acquire a copy straight away. Our idea was that this type of system will be targeted at airports and international train stations for long journeys.<br><br>
          The team and I employed the Star Lifecycle Model as the requirements were already provided, enabling flexibility to complete and evaluate stages
          of the model without any sort of order. The evaluation is centred which encourages iteration, when an activity is complete, we evaluate; user centred design.
          Usability Engineering principles such as affordance and color blindness was applied and the initial prototype has been created through ‘MarvelApp.’
        </p>
        <div class="col text-center">
          <button id="button" class="btn btn-primary btn-md" onclick="window.open('https://marvelapp.com/prototype/10b70ea9', '_blank')">MarvelApp</button>
        </div>
      </div>

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>Dice Roller (Android Application)</h4>
        </div>
        <p class="p-3">
          This was my first introduction to android development where I have created an android application that allows a user to type a number from 1-6,
          and click a button that generates a random number from 1-6 also. If the user's number and the random generator match then the user gets a point.
          Also, introducing to different activities where a user clicks a button and is navigated to a new activity.
        </p>
        <div class="col text-center">
          <button id="button" class="btn btn-primary btn-md" type="button" onclick="window.open('https://github.com/abdulnaseem/diceroller', '_blank')">GitHub</button>
        </div>
      </div>

      <div class="p-5 my-3 border" id="individual">
        <div class="col text-center">
          <h4>Finch Robot</h4>
        </div>
        <p class="p-3">
          I was given the finch robot from the university and chose the task ‘tilt control’ which was one of seven tasks provided for each group;
          group of 6, the tasks to be integrated towards the end of the year. My task involved moving the finch robot in four different directions
          such as forward, reverse, right or left. I utilised the Eclipse IDE, Java and the built in classes and methods to create a GUI that enables
          the user to choose the task at hand and the tilt controls.
        </p>
        <div class="col text-center">
          <button id="button" class="btn btn-primary btn-md" type="button" onclick="window.open('https://github.com/abdulnaseem/finchrobot-tiltcontrol', '_blank')">GitHub</button>
        </div>
      </div>

</div>

{% endblock %}